CREATE TABLE tb_setor (
                              id BIGINT AUTO_INCREMENT PRIMARY KEY,
                              nome VARCHAR(255) NOT NULL UNIQUE
);

-- Dados iniciais
INSERT INTO tb_setor (nome) VALUES
                                ('HRG-NPDOC'),
                                ('HRG-LABORATORIO'),
                                ('HRG-NRAD'),
                                ('HRG-NÚCLEO DE FARMÁCIA'),
                                ('HRG-NÚCLEO DE ALMOXARIFADO'),
                                ('HRG-BANCO DE SANGUE'),
                                ('HRG-NÚCLEO DE MANUT. E REPAROS'),
                                ('HRG-NARP'),
                                ('HRG-SERVIÇO SOCIAL'),
                                ('UBS PONTE ALTA NORTE'),
                                ('UBS PONTE ALTA'),
                                ('UBS ENGENHO DAS LAJES'),
                                ('UBS 01'),
                                ('UBS 02'),
                                ('UBS 03'),
                                ('UBS 04'),
                                ('UBS 05'),
                                ('UBS 06'),
                                ('BERÇÁRIO/MATERNIDADE'),
                                ('HRG-NÚCLEO DE TRANSPORTE'),
                                ('HRG-NÚCLEO DE BANCO DE LEITE'),
                                ('NVEPI (VIG. EPIDEMIOLÓGICA)'),
                                ('HRG-ANATOMIA'),
                                ('HRG-NGPESP GAMA'),
                                ('HRG-NME'),
                                ('HRG-GERÊNCIA DE EMERGÊNCIA'),
                                ('HRG-GAMAD'),
                                ('HRG-TISIOLOGIA'),
                                ('HRG-NCIH'),
                                ('HRG-NQSP'),
                                ('HRG-DIÁLISE'),
                                ('HRG-FISIOTERAPIA'),
                                ('ADM-REGIONAL'),
                                ('HRG-NUCAP'),
                                ('HRG-OUVIDORIA'),
                                ('HRG-PSA'),
                                ('HRSM-TRANSPORTE'),
                                ('HRG-LAVANDERIA'),
                                ('HRG-CENTRO CIRÚRGICO'),
                                ('DHRG'),
                                ('SRSSU - SUPERINTENDÊNCIA'),
                                ('HRG - NSHMT'),
                                ('HRG-NEPS'),
                                ('GETRAN-SAI'),
                                ('HRG-CENTRO OBSTÉTRICO'),
                                ('HRG-NÚCLEO GESTÃO DE CUSTOS'),
                                ('HRG-CLÍNICA MÉDICA'),
                                ('HRG-NAGMP'),
                                ('HRG-TERAPIA OCUPACIONAL'),
                                ('HRG-PAV'),
                                ('HRG-GER. ENFERMAGEM'),
                                ('HRG-NECFM'),
                                ('HRG-ODONTOLOGIA'),
                                ('HRG-PAI'),
                                ('HRG-NÚCLEO DE RADIOLOGIA'),
                                ('HRG-CLÍNICA CIRÚRGICA'),
                                ('HRG-INTERNAÇÃO PEDIATRIA'),
                                ('FARMÁCIA DE ALTO CUSTO'),
                                ('HRG-POLICLÍNICA'),
                                ('SRSSU - GAO (HRSM)'),
                                ('NQSP HRG'),
                                ('SRSSU - DIRETORIA ADMINISTRATIVA'),
                                ('HRG-NCE'),
                                ('HRG-HEMODIALISE'),
                                ('HRG-DIRAPS'),
                                ('HRG-GAOESP'),
                                ('HRG-NTINF'),
                                ('HRG-NND');