-- Criação da tabela carros
CREATE TABLE tb_carro (
                        id BIGINT PRIMARY KEY AUTO_INCREMENT,
                        modelo VARCHAR(50) NOT NULL,
                        marca VARCHAR(100) NOT NULL,
                        placa VARCHAR(10) NOT NULL UNIQUE
);

-- Inserção de 5 registros iniciais
INSERT INTO tb_carro (placa, modelo, marca) VALUES
                                                ('PBR2129', 'DOBLO', 'FIAT'),
                                                ('JIL1781', 'FURGÃO', 'FIAT'),
                                                ('PAE0967', 'AMBULANCIA', 'FIAT'),
                                                ('PAC0991', 'AMBULANCIA', 'FIAT'),
                                                ('PAC0992', 'AMBULANCIA', 'FIAT'),
                                                ('PBR2023', 'DOBLO', 'FIAT'),
                                                ('PBR5129', 'DOBLO', 'FIAT'),
                                                ('PAC6496', 'DOBLO', 'FIAT'),
                                                ('PAC6491', 'DOBLO', 'FIAT'),
                                                ('PBR2143', 'DOBLO', 'FIAT'),
                                                ('PAC9629', 'AMBULANCIA', 'FIAT'),
                                                ('JHN8453', 'PALIO', 'FIAT'),
                                                ('PAY9829', 'MOBI', 'FIAT'),
                                                ('PBR2159', 'DOBLO', 'FIAT'),
                                                ('JIL1661', 'FURGÃO', 'FIAT'),
                                                ('JIL1821', 'AMBULANCIA', 'FIAT'),
                                                ('PBR2027', 'DOBLO', 'FIAT'),
                                                ('PBR1995', 'FIAT', 'FIAT'),
                                                ('PAB9675', 'AMBULANCIA', 'FIAT'),
                                                ('PBW2068', 'DOBLO', 'FIAT'),
                                                ('PBN2068', 'DOBLO', 'FIAT'),
                                                ('PAC6509', 'DOBLO', 'FIAT'),
                                                ('OVT8816', 'AMBULANCIA', 'FIAT'),
                                                ('PAE1013', 'AMBULÂNCIA', 'FIAT'),
                                                ('PAC0993', 'AMBULÂNCIA', 'FIAT'),
                                                ('FQR2337', 'AMBULANCIA', 'FIAT'),
                                                ('JJJ3333', 'DUSTER', 'RENAULT'),
                                                ('GPU0050', 'CLIO', 'RENAULT'),
                                                ('PAC0093', 'MASTER', 'RENAULT'),
                                                ('PAC0967', 'MASTER', 'RENAULT'),
                                                ('JJL1820', 'FOCUS', 'FIAT'),
                                                ('QXB9123', 'DOBLO', 'FIAT'),
                                                ('PAC0998', 'MASTER', 'RENAULT'),
                                                ('JIL1820', 'MASTER', 'RENAULT'),
                                                ('JJI1820', 'MASTER', 'RENAULT'),
                                                ('PBR1994', 'DOBLO', 'FIAT'),
                                                ('PBR7994', 'DOBLO', 'FIAT'),
                                                ('SSF0700', 'ONIX', 'CHEVROLET'),
                                                ('SSF0070', 'ONIX', 'CHEVROLET'),
                                                ('SSK0929', 'SPIN', 'CHEVROLET'),
                                                ('SSL0045', 'SPIN', 'CHEVROLET'),
                                                ('SSL0010', 'SPIN', 'CHEVROLET'),
                                                ('SSL0023', 'SPIN', 'CHEVROLET');
